name: Examples 

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
        working-directory: packages/next-broken-links
      - name: Build example
        run: bun run build
        working-directory: examples/static-export
      - name: Check links
        # expect to fail
        run: (bun run ../../packages/next-broken-links/dist/index.js && exit 1) || exit 0
        working-directory: examples/static-export
