name: Examples 

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NEXT_TELEMETRY_DISABLED: 1
  EXPECTED_COUNT: 5

jobs:
  output:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OUTPUT_MODE: ["export", "undefined"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        working-directory: packages/next-broken-links
        run: bun run build

      - name: Replace export option
        working-directory: examples/static-export
        if: matrix.OUTPUT_MODE == 'undefined'
        run: sed -i 's/"export"/undefined/' next.config.ts && cat next.config.ts

      - name: Build example
        working-directory: examples/static-export
        run: bun run build

      - name: Check links
        working-directory: examples/static-export
        run: |
          output=$(bun run ../../packages/next-broken-links/dist/index.js --domain vahor.fr || true)
          echo "$output"
          actual_count=$(echo "$output" | grep -o "Found [0-9]* broken links" | grep -o "[0-9]*")
          actual_count=${actual_count:-0}
          echo "(debug) Found $actual_count broken links"
          if [ "$actual_count" -ne "$EXPECTED_COUNT" ]; then
            echo "(debug) Expected $EXPECTED_COUNT broken links"
            exit 1
          fi

